### ISSUE TITLE
prefix commands

### ISSUE THREAD

**Issue by Sasukezynho** [Alien-alfa/WhatsAppBot-MD#2]
would you like to put the option to use prefix? sometimes it gets in the way of group conversations.

**Comment by Alien-alfa** [comment]
ok I will ad a option to set prefix in next update

**Comment by Sasukezynho** [comment]
u the best man s22

**Comment by salman0ansari** [comment]
@Alien-alfa which Obfuscator did u used?

**Comment by Alien-Alfa** [comment]
yup I will look into that add key PREFIX in Heroku Config Vars and try
